version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: inflacion
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
